<?php

return [

    'AWS_ACCESS_KEY_ID' => env('AWS_ACCESS_KEY_ID'),
    'AWS_SECRET_ACCESS_KEY' => env('AWS_SECRET_ACCESS_KEY'),
    'AWS_DEFAULT_REGION' => env('AWS_DEFAULT_REGION'),
    'AWS_BUCKET' => env('AWS_BUCKET'),
    'AWS_S3_VERSION' => env('AWS_S3_VERSION'),
    'AWS_BUCKET_FILE_VISIBILITY' => env('AWS_BUCKET_FILE_VISIBILITY'),


    'GOOGLE_MAPS_KEY' => env('GOOGLE_MAPS_KEY'),


    'FCM_KEY' => env('FCM_KEY'),


    'GOOGLE_ID' => env('GOOGLE_ID'),
    'GOOGLE_SECRET' => env('GOOGLE_SECRET'),
    'GOOGLE_URL' => env('GOOGLE_URL'),


    'TWILIO_ACCOUNT_SID' => env('TWILIO_ACCOUNT_SID'),
    'TWILIO_AUTH_TOKEN' => env('TWILIO_AUTH_TOKEN'),
    'TWILIO_NUMBER' => env('TWILIO_NUMBER'),


    'STRIPE_SECRET_KEY' => env('STRIPE_SECRET_KEY'),
    'STRIPE_PUBLISHABLE_KEY' => env('STRIPE_PUBLISHABLE_KEY'),


    'GOOGLE_PLAYSTORE_URL' => env('GOOGLE_PLAYSTORE_URL'),
    'APPLE_APPSTORE_URL' => env('APPLE_APPSTORE_URL'),


    'ADMIN_ROUTE_PREFIX' => env('ADMIN_ROUTE_PREFIX'),
    'APP_NAME' => env('APP_NAME'),

    'PASSPORT_TOKEN_KEY' => env('PASSPORT_TOKEN_KEY'),

    'TWILLO_SID' => env('TWILLO_SID'),
    'TWILLO_TOKEN' => env('TWILLO_TOKEN'),

    'PAYGATE_ID' => env('PAYGATE_ID'),
    'PAYGATE_SECRET' => env('PAYGATE_SECRET'),


    'AWS_ACCESS_KEY_ID' => env('AWS_ACCESS_KEY_ID'),
    'AWS_SECRET_ACCESS_KEY' => env('AWS_SECRET_ACCESS_KEY'),
    'AWS_DEFAULT_REGION' => env('AWS_DEFAULT_REGION'),
    'AWS_BUCKET' => env('AWS_BUCKET'),
    'S3_PATH'=> env('S3_PATH'),
];
